### ISSUE TITLE
I can't update a record with Angularjs $http.put()

### ISSUE THREAD

**Issue by 0noel0** [mevdschee/mysql-crud-api#5] opened 2015-10-16 09:02 UTC
This is my code:
.factory('Cap',function($http){
    var url = 'http://localhost/mysql-crud-api/api.php/cap/1/';
    var dd = {};
    dd.gData = function(){
         var data = ({
                tot : 99,//This is the field that I want to update.
            });
        return $http.put(url,data);
    }
    console.log(dd);
    return dd;
});

This is the response:

OPTIONS http://localhost/mysql-crud-api/api.php/caps/1/ (anonymous function) @ ionic.bundle.js:18526sendReq @ ionic.bundle.js:18327status.$get.serverRequest @ ionic.bundle.js:18043processQueue @ ionic.bundle.js:21888(anonymous function) @ ionic.bundle.js:21904promises.$get.Scope.$eval @ ionic.bundle.js:23100promises.$get.Scope.$digest @ ionic.bundle.js:22916promises.$get.Scope.$apply @ ionic.bundle.js:23205done @ ionic.bundle.js:18358completeRequest @ ionic.bundle.js:18548requestLoaded @ ionic.bundle.js:18489
(index):1 

XMLHttpRequest cannot load http://localhost/mysql-crud-api/api.php/cap/1/. Response for preflight has invalid HTTP status code 404

I've been 6 hours and not find the problem.

P.D. It works perfectly if I do with Advanced Rest Client (Chrome Extension)
URL Extension: https://chrome.google.com/webstore/detail/advanced-rest-client/hgmloofddffdnphfgcellkdfbfbjeloo?utm_source=gmail

Thanks for the help!!!

**Comment by mevdschee** [comment] 2015-10-16 09:28
"99" has a trailing comma

**Comment by mevdschee** [comment] 2015-10-16 09:29
I think the problem is with the options request, let me test it locally. Hang on..

**Comment by mevdschee** [comment] 2015-10-16 09:43
Update: I confirmed it is the pre-flight or options request that gives a 404.

**Comment by mevdschee** [comment] 2015-10-16 10:00
Update: Reading an extensive [mozilla article](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS?redirectlocale=en-US&redirectslug=HTTP_access_control) on the subject. I will implement a fix.

**Comment by mevdschee** [comment] 2015-10-16 10:33
Update: Should be fixed in 54e312f27904fb4377e1aec0358a325fd3f48fcf

**Comment by mevdschee** [comment] 2015-10-16 10:37
Let me know whether or not it works for you.

**Comment by 0noel0** [comment] 2015-10-16 17:12
It works great !!!, thank you very much. you saved me.

Just something for documentation, you must use an extension for CORS or add the header "header ('Access-Control-Allow-Origin: *');" api.php in the file to allow make the request.

Thanks again for your time, keep it up !!!
Noob developers appreciate this help !!!

**Closed** 2015-10-16 17:21 UTC
Labels: enhancement

**Comment by mevdschee** [comment] 2015-10-16 20:28
@0noel0 Does the latest version still need the extra "header('Access-Control-Allow-Origin: *');" call? That should not be necessary. Please let me know.

**Comment by 0noel0** [comment] 2015-10-17 04:08
I had not really tested the effect of the header, it does not affect whether or not it gets, but the extension of CORS if necessary.

This is the error in console without the extension:

XMLHttpRequest cannot load http://localhost/mysql-crud-api/api.php/cap/1/. Request header field Content-Type is not allowed by Access-Control-Allow-Headers.

I use the CORS (Chrome extension)
URL:https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?utm_source=gmail

And to enable this extension does not return the error appears.
Only return 1 (Success).

But as far as if this is not an error.

**Comment by mevdschee** [comment] 2015-10-17 13:39
>Request header field Content-Type is not allowed by Access-Control-Allow-Headers.
I fixed this one by adding: `Access-Control-Allow-Headers: Content-Type`

Can you try again?

**Comment by mevdschee** [comment] 2015-10-17 19:43
Added an AngularJS example in d69fa4d861099906d3d831d62afcffa6658ba2a1
